cookie:
  expiry_days: 7
  key: change-me-cookie-key
  name: jwt-user-mgmt-admin
credentials:
  usernames:
    admin:
      email: admin@example.com
      failed_login_attempts: 0
      first_name: Admin
      last_name: User
      logged_in: false
      password: admin
      roles:
      - admin
pre-authorized:
  emails: []

